//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Post = new HashSet<Post>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Slug { get; set; }
    
        public virtual ICollection<Post> Post { get; set; }
    }
}
